ALTER TABLE Orders
    MODIFY OrderID int NOT NULL AUTO_INCREMENT;

ALTER TABLE Payment
    MODIFY PaymentID int NOT NULL AUTO_INCREMENT;

ALTER TABLE Product
    MODIFY ProductID int NOT NULL AUTO_INCREMENT;
